### ISSUE TITLE
Comparison to recent-menu

### ISSUE THREAD

**Issue by Zabooby** [po5/memo#1]
I am currently using [recent-menu](https://github.com/natural-harmonia-gropius/recent-menu) (with uosc), how does this compare, any obvious advantages?

Nvm, didn't read the full reademe.

**Comment by po5** [comment]
Now has more features like two-way history browsing, text truncation that preserves extensions, "open last" keybind, `hide_same_dir` as an efficient alternative to recent-menu's `ignore_same_series` that works the same in real use cases.

Added instructions for disabling history on specific files.

Since the script can read through the history file efficiently I want to add a search feature, but that will take a bit longer.

@Zabooby Please tell me if there's anything else that you think will improve the script.

**Comment by Zabooby** [comment]
Honestly, feature wise I am fine with the core functions that both provide but if there are any performance improvements to be made that would be great. I will definitely do some tests/comparisons, I might even find some of the extra features useful!
