### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by itsmeipg** [po5/memo#41]
Using latest version of memo and uosc 5.6.2, I get a blank 6th page with exactly 50 items in history.
![image](https://github.com/user-attachments/assets/4ed10522-a280-4c8c-b14c-f11c29f43f70)
(Title and next/prev button strings are edited, though I did not change anything else in memo).

**Comment by po5** [comment]
That's not related to any update, it's just something that can happen when any of the `hide_*` options are enabled due to the design.
What's happening is that you had enough entries to fill out an entire page, but the reading cursor had not reached the end of the file (there were still entries to read, so there is a "next" button).
Once you navigate the next page it starts reading the remaining entries and it just so happens that all of them matched a hide condition (either files that were already displayed on previous pages, or files that have since been deleted).
This is intended behavior, and not a bug.
